/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: EddyNL (https://sketchfab.com/EddyNL)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-rocket-ba16c6e764d24af7a376fa50aa927ab5
title: Cartoon Rocket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cartoon_rocket({ ref, positionArray, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cartoon_rocket.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={positionArray} rotation={[5, 5, 2]} scale={0.6}>
        <group ref={ref} rotation={[Math.PI / -7, 2, 10]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Cone} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Fins} />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.Rings}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.Window}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.Rings}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.Rings}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Thruster}
          />
          {/* <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials['Rings.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials['Body.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials['Cone.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials['Fins.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials['Rings.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials['Rings.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials['Thruster.001']}
            />
          </group>
          <group position={[0, 0, -3.32]}>
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials['Window.001']}
            />
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cartoon_rocket.gltf')
