/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: drei.lu (https://sketchfab.com/drei.lu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RocketAsteroid({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rocketAsteroid.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[0, 0.02, -6.33]}
          rotation={[0.24, -0.55, 0.56]}
          scale={1}
        >
          <mesh
            geometry={nodes.planet001_1.geometry}
            material={materials.scene}
          />
          <mesh
            geometry={nodes.planet001_2.geometry}
            material={materials.scene}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocketAsteroid.gltf')
